// MBA301 Framework Library — Per-Unit PDF page mapping
// Auto-generated; page 1 of each PDF is the unit divider; pages 2-16 are the 15 framework sheets
// Usage: window.MBA301_PAGES[unitN]['Framework Name'] -> page number
window.MBA301_PAGES = {
  "1": {
    "Brown's Triple Loop": 2,
    "Stanford 5-Stage": 3,
    "Double Diamond": 4,
    "DVF Framework": 5,
    "3-i Framework": 6,
    "Liedtka's 4 Truths": 7,
    "Dosi's 10-Dim Mindset": 8,
    "Kelley's Creative Confidence": 9,
    "Buchanan's Wicked Problems": 10,
    "Mindset · Process · Toolbox": 11,
    "Empathy Map": 12,
    "Personas": 13,
    "Customer Journey Map": 14,
    "5 Whys": 15,
    "How Might We (HMW)": 16
  },
  "2": {
    "Crazy 8s": 2,
    "SCAMPER": 3,
    "Brainwriting 6-3-5": 4,
    "Analogies & Random Stimulus": 5,
    "Worst Possible Ideas": 6,
    "Dot Voting": 7,
    "NUF Test": 8,
    "Impact-Effort Matrix": 9,
    "2×2 Decision Matrix": 10,
    "How-Now-Wow": 11,
    "Google Design Sprint": 12,
    "GV Sprint 2.0": 13,
    "Idea Speed-Dating": 14,
    "Lightning Decision Jam": 15,
    "Sprint Retrospective": 16
  },
  "3": {
    "Porter's 5 Forces": 2,
    "VRIO": 3,
    "PESTEL": 4,
    "SWOT Recast": 5,
    "Value Chain": 6,
    "Strategy Canvas": 7,
    "ERRC Grid": 8,
    "4 Actions Framework": 9,
    "Value Curve": 10,
    "6 Paths Framework": 11,
    "BMC 9 Blocks": 12,
    "Value Proposition Canvas": 13,
    "BMC Patterns": 14,
    "Platform Business Model": 15,
    "Revenue Model Typology": 16
  },
  "4": {
    "Bird-in-Hand": 2,
    "Affordable Loss": 3,
    "Lemonade": 4,
    "Crazy Quilt": 5,
    "Pilot-in-the-Plane": 6,
    "Knight's Risk vs Uncertainty": 7,
    "Possibility Quadrant": 8,
    "Real Options Lens": 9,
    "Pre-Mortem": 10,
    "Black Swan & Antifragility": 11,
    "Causal vs Effectual": 12,
    "Opportunity Recognition": 13,
    "Bias for Action": 14,
    "Growth vs Fixed Mindset": 15,
    "Entrepreneurial Orientation": 16
  },
  "5": {
    "JTBD Canvas": 2,
    "Outcome-Driven Innovation": 3,
    "Progress Made Easier": 4,
    "Switch Interview · 4 Forces": 5,
    "Job Map": 6,
    "Lean Canvas (9 Blocks)": 7,
    "Problem-Solution Fit": 8,
    "Product-Market Fit": 9,
    "Lean Stack": 10,
    "Traction Canvas": 11,
    "Kano Model": 12,
    "MVP Ladder": 13,
    "Build-Measure-Learn": 14,
    "Riskiest Assumption Test": 15,
    "Pretotyping": 16
  },
  "6": {
    "Blank's 4 Steps": 2,
    "Discovery Interviews": 3,
    "Validation Experiments": 4,
    "AARRR · Pirate Metrics": 5,
    "Pivot Types": 6,
    "Bootstrapping": 7,
    "FFF + Angel": 8,
    "Seed Round": 9,
    "Series A/B/C": 10,
    "Cap Table Dynamics": 11,
    "CAC": 12,
    "LTV": 13,
    "LTV/CAC Ratio": 14,
    "Payback Period": 15,
    "Contribution Margin & Burn": 16
  },
  "7": {
    "Internal Incubator": 2,
    "Corporate Accelerator": 3,
    "Venture Studio": 4,
    "Corporate VC (CVC)": 5,
    "Spin-out / Spin-in": 6,
    "Skunk Works Model": 7,
    "Ambidextrous Organisation": 8,
    "10-Week Accelerator": 9,
    "Sponsor-Engineer Model": 10,
    "Innovation Outpost": 11,
    "Stage-Gate Process": 12,
    "Sponsor Council": 13,
    "Kill Criteria": 14,
    "Demo Day": 15,
    "Internal Term Sheet": 16
  },
  "8": {
    "Distill-Decompose-Prioritise": 2,
    "Message Strategy Spectrum": 3,
    "Vehicles for Ideas": 4,
    "Message-Market Fit": 5,
    "One-Sentence Pitch": 6,
    "Miller's 7-Part Story": 7,
    "Hero's Journey": 8,
    "Pixar's 6-Step Spine": 9,
    "Before-After-Bridge": 10,
    "Problem-Agitate-Solve": 11,
    "Kawasaki's 10/20/30": 12,
    "Sequoia Structure": 13,
    "Airbnb Slide Template": 14,
    "Investor Deck Anatomy": 15,
    "3-Minute Pitch": 16
  },
  "9": {
    "Iceberg · 4 Levels": 2,
    "Events → Patterns": 3,
    "Surface vs Deep": 4,
    "Systems Boundaries": 5,
    "Double-Loop Learning": 6,
    "12 Leverage Points": 7,
    "Parameters & Buffers": 8,
    "Feedback Loops": 9,
    "Goals of the System": 10,
    "Paradigm Shift": 11,
    "Systems Archetypes (8)": 12,
    "Shifting the Burden": 13,
    "Tragedy of the Commons": 14,
    "Theory U": 15,
    "Presencing": 16
  }
};